name: exam_productive_5
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: any
  gap: ^3.0.1
  flutter_bloc: ^8.1.3
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Light.ttf
        - asset: assets/fonts/Barlow-LightItalic.ttf
        - asset: assets/fonts/Barlow-Thin.ttf
        - asset: assets/fonts/Barlow-ThinItalic.ttf
        - asset: assets/fonts/Barlow-Regular.ttf
        - asset: assets/fonts/Barlow-Italic.ttf
        - asset: assets/fonts/Barlow-Medium.ttf
        - asset: assets/fonts/Barlow-MediumItalic.ttf
        - asset: assets/fonts/Barlow-SemiBold.ttf
        - asset: assets/fonts/Barlow-SemiBoldItalic.ttf
        - asset: assets/fonts/Barlow-Bold.ttf
        - asset: assets/fonts/Barlow-BoldItalic.ttf
        - asset: assets/fonts/Barlow-ExtraBold.ttf
        - asset: assets/fonts/Barlow-ExtraBoldItalic.ttf
        - asset: assets/fonts/Barlow-Black.ttf
        - asset: assets/fonts/Barlow-BlackItalic.ttf
